"""Import/export helpers for drawings and animations."""

from __future__ import annotations

import textwrap
import zipfile
from pathlib import Path

from PIL import Image, ImageEnhance

from .protocol import MATRIX_SIZE, PIXEL_COUNT
from .settings import MAX_ANIM_PANELS

Frame = list[tuple[int, int, int]]


def _clamp_frame(pixels: Frame) -> Frame:
    if len(pixels) != PIXEL_COUNT:
        raise ValueError(f"expected {PIXEL_COUNT} pixels, got {len(pixels)}")
    out: Frame = []
    for r, g, b in pixels:
        out.append(
            (
                max(0, min(255, int(r))),
                max(0, min(255, int(g))),
                max(0, min(255, int(b))),
            )
        )
    return out


def frame_to_image(pixels: Frame, *, scale: int = 1) -> Image.Image:
    pixels = _clamp_frame(pixels)
    scale = max(1, int(scale))
    img = Image.new("RGB", (MATRIX_SIZE, MATRIX_SIZE))
    img.putdata(pixels)
    if scale != 1:
        img = img.resize(
            (MATRIX_SIZE * scale, MATRIX_SIZE * scale),
            Image.Resampling.NEAREST,
        )
    return img


def image_to_frame(
    img: Image.Image,
    *,
    saturation: float = 1.35,
    contrast: float = 1.1,
) -> Frame:
    frame = img.convert("RGBA")
    background = Image.new("RGBA", frame.size, (0, 0, 0, 255))
    composited = Image.alpha_composite(background, frame).convert("RGB")
    resized = composited.resize((MATRIX_SIZE, MATRIX_SIZE), Image.Resampling.LANCZOS)
    boosted = ImageEnhance.Color(resized).enhance(saturation)
    boosted = ImageEnhance.Contrast(boosted).enhance(contrast)
    pixels: Frame = []
    for y in range(MATRIX_SIZE):
        for x in range(MATRIX_SIZE):
            r, g, b = boosted.getpixel((x, y))
            pixels.append((int(r), int(g), int(b)))
    return pixels


def save_frame_png(path: str | Path, pixels: Frame, *, scale: int = 16) -> None:
    path = Path(path)
    frame_to_image(pixels, scale=scale).save(path, format="PNG")


def load_frame_png(path: str | Path) -> Frame:
    with Image.open(path) as img:
        return image_to_frame(img)


def _format_pixel_tuple(px: tuple[int, int, int]) -> str:
    return f"({px[0]}, {px[1]}, {px[2]})"


def _format_frame_literal(pixels: Frame, indent: str = "    ") -> str:
    rows: list[str] = []
    for y in range(MATRIX_SIZE):
        row = pixels[y * MATRIX_SIZE : (y + 1) * MATRIX_SIZE]
        rows.append(indent + ", ".join(_format_pixel_tuple(px) for px in row) + ",")
    return "\n".join(rows)


def save_drawing_python(path: str | Path, pixels: Frame, *, name: str = "drawing") -> None:
    pixels = _clamp_frame(pixels)
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name) or "drawing"
    body = textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """MI LED drawing export ({MATRIX_SIZE}x{MATRIX_SIZE}).

        Generated by mi-led-gui. PIXEL_COUNT = {PIXEL_COUNT}.
        """

        MATRIX_SIZE = {MATRIX_SIZE}
        PIXEL_COUNT = {PIXEL_COUNT}

        # Row-major RGB triples.
        {safe.upper()}_PIXELS = [
        {_format_frame_literal(pixels)}
        ]


        def get_pixels():
            return list({safe.upper()}_PIXELS)


        if __name__ == "__main__":
            px = get_pixels()
            print(f"{safe}: {{len(px)}} pixels")
            nonzero = sum(1 for c in px if c != (0, 0, 0))
            print(f"lit cells: {{nonzero}}")
        '''
    )
    Path(path).write_text(body, encoding="utf-8")


def save_animation_python(
    path: str | Path,
    frames: list[Frame],
    *,
    frame_ms: int = 200,
    name: str = "animation",
) -> None:
    if not frames:
        raise ValueError("no frames to export")
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name) or "animation"
    chunks = []
    for i, frame in enumerate(frames):
        chunks.append(f"    # Panel {i + 1}\n    [\n{_format_frame_literal(_clamp_frame(frame), '        ')}\n    ],")
    frames_block = "\n".join(chunks)
    body = textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """MI LED animation export ({MATRIX_SIZE}x{MATRIX_SIZE}, {len(frames)} panels).

        Generated by mi-led-gui.
        """

        MATRIX_SIZE = {MATRIX_SIZE}
        PIXEL_COUNT = {PIXEL_COUNT}
        FRAME_MS = {int(frame_ms)}

        {safe.upper()}_FRAMES = [
        {frames_block}
        ]


        def get_frames():
            return [list(frame) for frame in {safe.upper()}_FRAMES]


        if __name__ == "__main__":
            frames = get_frames()
            print(f"{safe}: {{len(frames)}} panels x {{len(frames[0])}} pixels")
            print(f"suggested frame delay: {{FRAME_MS}} ms")
        '''
    )
    Path(path).write_text(body, encoding="utf-8")


def save_animation_zip(path: str | Path, frames: list[Frame], *, scale: int = 16) -> None:
    if not frames:
        raise ValueError("no frames to export")
    path = Path(path)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for i, frame in enumerate(frames):
            img = frame_to_image(frame, scale=scale)
            buf_name = f"panel_{i + 1:02d}.png"
            from io import BytesIO

            bio = BytesIO()
            img.save(bio, format="PNG")
            zf.writestr(buf_name, bio.getvalue())


def save_animation_gif(
    path: str | Path,
    frames: list[Frame],
    *,
    frame_ms: int = 200,
    scale: int = 16,
) -> None:
    if not frames:
        raise ValueError("no frames to export")
    images = [frame_to_image(f, scale=scale) for f in frames]
    duration = max(20, int(frame_ms))
    images[0].save(
        path,
        format="GIF",
        save_all=True,
        append_images=images[1:],
        duration=duration,
        loop=0,
        disposal=2,
    )


def load_animation_gif(
    path: str | Path,
    *,
    max_frames: int = MAX_ANIM_PANELS,
) -> list[Frame]:
    path = Path(path)
    frames: list[Frame] = []
    with Image.open(path) as img:
        n = int(getattr(img, "n_frames", 1) or 1)
        for i in range(min(n, max_frames)):
            img.seek(i)
            frames.append(image_to_frame(img.copy()))
    if not frames:
        raise ValueError("GIF contained no frames")
    return frames


def load_animation_zip(path: str | Path, *, max_frames: int = MAX_ANIM_PANELS) -> list[Frame]:
    path = Path(path)
    frames: list[Frame] = []
    with zipfile.ZipFile(path, "r") as zf:
        names = sorted(
            n
            for n in zf.namelist()
            if n.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".webp"))
            and not n.endswith("/")
        )
        if not names:
            raise ValueError("ZIP contained no images")
        from io import BytesIO

        for name in names[:max_frames]:
            data = zf.read(name)
            with Image.open(BytesIO(data)) as img:
                frames.append(image_to_frame(img))
    return frames
