"""Import/export helpers for drawings and animations."""

from __future__ import annotations

import ast
import zipfile
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageEnhance

from .protocol import MATRIX_SIZE, PIXEL_COUNT
from .settings import MAX_ANIM_PANELS

Frame = list[tuple[int, int, int]]


def _clamp_frame(pixels: Frame) -> Frame:
    if len(pixels) != PIXEL_COUNT:
        raise ValueError(f"expected {PIXEL_COUNT} pixels, got {len(pixels)}")
    out: Frame = []
    for r, g, b in pixels:
        out.append(
            (
                max(0, min(255, int(r))),
                max(0, min(255, int(g))),
                max(0, min(255, int(b))),
            )
        )
    return out


def frame_to_image(pixels: Frame, *, scale: int = 1) -> Image.Image:
    pixels = _clamp_frame(pixels)
    scale = max(1, int(scale))
    img = Image.new("RGB", (MATRIX_SIZE, MATRIX_SIZE))
    img.putdata(pixels)
    if scale != 1:
        img = img.resize(
            (MATRIX_SIZE * scale, MATRIX_SIZE * scale),
            Image.Resampling.NEAREST,
        )
    return img


def image_to_frame(
    img: Image.Image,
    *,
    saturation: float = 1.35,
    contrast: float = 1.1,
) -> Frame:
    frame = img.convert("RGBA")
    background = Image.new("RGBA", frame.size, (0, 0, 0, 255))
    composited = Image.alpha_composite(background, frame).convert("RGB")
    resized = composited.resize((MATRIX_SIZE, MATRIX_SIZE), Image.Resampling.LANCZOS)
    boosted = ImageEnhance.Color(resized).enhance(saturation)
    boosted = ImageEnhance.Contrast(boosted).enhance(contrast)
    pixels: Frame = []
    for y in range(MATRIX_SIZE):
        for x in range(MATRIX_SIZE):
            r, g, b = boosted.getpixel((x, y))
            pixels.append((int(r), int(g), int(b)))
    return pixels


def save_frame_png(path: str | Path, pixels: Frame, *, scale: int = 16) -> None:
    path = Path(path)
    frame_to_image(pixels, scale=scale).save(path, format="PNG")


def load_frame_png(path: str | Path) -> Frame:
    with Image.open(path) as img:
        return image_to_frame(img)


def _format_pixel_tuple(px: tuple[int, int, int]) -> str:
    return f"({px[0]}, {px[1]}, {px[2]})"


def _format_frame_literal(pixels: Frame, indent: str = "    ") -> str:
    rows: list[str] = []
    for y in range(MATRIX_SIZE):
        row = pixels[y * MATRIX_SIZE : (y + 1) * MATRIX_SIZE]
        rows.append(indent + ", ".join(_format_pixel_tuple(px) for px in row) + ",")
    return "\n".join(rows)


def save_drawing_python(path: str | Path, pixels: Frame, *, name: str = "drawing") -> None:
    pixels = _clamp_frame(pixels)
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name) or "drawing"
    pixels_name = f"{safe.upper()}_PIXELS"
    body = (
        "#!/usr/bin/env python3\n"
        f'"""MI LED drawing export ({MATRIX_SIZE}x{MATRIX_SIZE}).\n'
        "\n"
        "Generated by mi-led-gui. "
        f"PIXEL_COUNT = {PIXEL_COUNT}.\n"
        '"""\n'
        "\n"
        f"MATRIX_SIZE = {MATRIX_SIZE}\n"
        f"PIXEL_COUNT = {PIXEL_COUNT}\n"
        "\n"
        "# Row-major RGB triples.\n"
        f"{pixels_name} = [\n"
        f"{_format_frame_literal(pixels)}\n"
        "]\n"
        "\n"
        "\n"
        "def get_pixels():\n"
        f"    return list({pixels_name})\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    px = get_pixels()\n"
        f'    print(f"{safe}: {{len(px)}} pixels")\n'
        "    nonzero = sum(1 for c in px if c != (0, 0, 0))\n"
        '    print(f"lit cells: {nonzero}")\n'
    )
    Path(path).write_text(body, encoding="utf-8")


def save_animation_python(
    path: str | Path,
    frames: list[Frame],
    *,
    frame_ms: int = 200,
    name: str = "animation",
) -> None:
    if not frames:
        raise ValueError("no frames to export")
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name) or "animation"
    frames_name = f"{safe.upper()}_FRAMES"
    chunks = []
    for i, frame in enumerate(frames):
        chunks.append(
            f"    # Panel {i + 1}\n"
            f"    [\n"
            f"{_format_frame_literal(_clamp_frame(frame), '        ')}\n"
            f"    ],"
        )
    frames_block = "\n".join(chunks)
    body = (
        "#!/usr/bin/env python3\n"
        f'"""MI LED animation export ({MATRIX_SIZE}x{MATRIX_SIZE}, {len(frames)} panels).\n'
        "\n"
        "Generated by mi-led-gui.\n"
        '"""\n'
        "\n"
        f"MATRIX_SIZE = {MATRIX_SIZE}\n"
        f"PIXEL_COUNT = {PIXEL_COUNT}\n"
        f"FRAME_MS = {int(frame_ms)}\n"
        "\n"
        f"{frames_name} = [\n"
        f"{frames_block}\n"
        "]\n"
        "\n"
        "\n"
        "def get_frames():\n"
        f"    return [list(frame) for frame in {frames_name}]\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    frames = get_frames()\n"
        f'    print(f"{safe}: {{len(frames)}} panels x {{len(frames[0])}} pixels")\n'
        '    print(f"suggested frame delay: {FRAME_MS} ms")\n'
    )
    Path(path).write_text(body, encoding="utf-8")


def _as_rgb_triple(value: object) -> tuple[int, int, int]:
    if not isinstance(value, (list, tuple)) or len(value) != 3:
        raise ValueError("pixel must be an (r, g, b) triple")
    r, g, b = value
    return (int(r) & 0xFF, int(g) & 0xFF, int(b) & 0xFF)


def _frame_from_literal(value: object) -> Frame:
    if not isinstance(value, (list, tuple)):
        raise ValueError("frame must be a list of pixels")
    if len(value) != PIXEL_COUNT:
        raise ValueError(f"expected {PIXEL_COUNT} pixels, got {len(value)}")
    return [_as_rgb_triple(px) for px in value]


def _python_list_assignments(path: str | Path) -> list[tuple[str, object]]:
    source = Path(path).read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    out: list[tuple[str, object]] = []
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        try:
            value = ast.literal_eval(node.value)
        except Exception:
            continue
        if isinstance(value, (list, tuple)):
            out.append((target.id, value))
    return out


def load_drawing_python(path: str | Path) -> Frame:
    assignments = _python_list_assignments(path)
    for name, value in assignments:
        if name.endswith("_PIXELS") or name in {"PIXELS", "DRAWING_PIXELS", "FRAME", "IMAGE"}:
            return _frame_from_literal(value)
    for _name, value in assignments:
        try:
            return _frame_from_literal(value)
        except ValueError:
            continue
    raise ValueError("no MI LED drawing pixels found in Python file")


def load_animation_python(
    path: str | Path, *, max_frames: int = MAX_ANIM_PANELS
) -> list[Frame]:
    assignments = _python_list_assignments(path)
    candidates: list[object] = []
    for name, value in assignments:
        if name.endswith("_FRAMES") or name in {"FRAMES", "PANELS", "ANIMATION_FRAMES"}:
            candidates.insert(0, value)
        else:
            candidates.append(value)
    for value in candidates:
        if not isinstance(value, (list, tuple)) or not value:
            continue
        # Flat single-frame pixel list.
        if len(value) == PIXEL_COUNT and isinstance(value[0], (list, tuple)) and len(value[0]) == 3:
            return [_frame_from_literal(value)]
        # List of frames.
        if isinstance(value[0], (list, tuple)) and value[0] and isinstance(value[0][0], (list, tuple)):
            frames = [_frame_from_literal(frame) for frame in value[:max_frames]]
            if frames:
                return frames
    raise ValueError("no MI LED animation frames found in Python file")


def save_animation_zip(path: str | Path, frames: list[Frame], *, scale: int = 16) -> None:
    if not frames:
        raise ValueError("no frames to export")
    path = Path(path)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for i, frame in enumerate(frames):
            img = frame_to_image(frame, scale=scale)
            buf_name = f"panel_{i + 1:02d}.png"
            bio = BytesIO()
            img.save(bio, format="PNG")
            zf.writestr(buf_name, bio.getvalue())


def save_animation_gif(
    path: str | Path,
    frames: list[Frame],
    *,
    frame_ms: int = 200,
    scale: int = 16,
) -> None:
    if not frames:
        raise ValueError("no frames to export")
    images = [frame_to_image(f, scale=scale) for f in frames]
    duration = max(20, int(frame_ms))
    images[0].save(
        path,
        format="GIF",
        save_all=True,
        append_images=images[1:],
        duration=duration,
        loop=0,
        disposal=2,
    )


def load_animation_gif(
    path: str | Path,
    *,
    max_frames: int = MAX_ANIM_PANELS,
) -> list[Frame]:
    path = Path(path)
    frames: list[Frame] = []
    with Image.open(path) as img:
        n = int(getattr(img, "n_frames", 1) or 1)
        for i in range(min(n, max_frames)):
            img.seek(i)
            frames.append(image_to_frame(img.copy()))
    if not frames:
        raise ValueError("GIF contained no frames")
    return frames


def load_animation_zip(path: str | Path, *, max_frames: int = MAX_ANIM_PANELS) -> list[Frame]:
    path = Path(path)
    frames: list[Frame] = []
    with zipfile.ZipFile(path, "r") as zf:
        names = sorted(
            n
            for n in zf.namelist()
            if n.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".webp"))
            and not n.endswith("/")
        )
        if not names:
            raise ValueError("ZIP contained no images")
        from io import BytesIO

        for name in names[:max_frames]:
            data = zf.read(name)
            with Image.open(BytesIO(data)) as img:
                frames.append(image_to_frame(img))
    return frames
